variant: fcos
version: 1.4.0
kernel_arguments:
  should_exist:
    - systemd.unified_cgroup_hierarchy=0
    - mitigations=off
  should_not_exist:
    - mitigations=auto,nosmt
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "__SSH_KEY_VALUE__"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBFcglMr3lhTiz9fMD2F6wc4N2vquMLfdPVWQBTwSrMx4by4kEFDoETtDVQfDr5fGuwRGqYEQBZ7eCVgZ4xbzeLpwjIXglOf4h2G6HTTJwvHQEYP0xm/3GJqqVS/eFnQJTW9AZPFddaedkP7lKxsMiCgnrB1LugPpc55nMcNS671+R9KiU0lr/+H42OuHJiiK7urvXLZYKXrPK6NWsY1aVBFEasaLTl/OSIt8e71PqlArDZ9oGj8iHdwt8IXmBWE99s1DhbdwJ3ui6bEi50CkVNCjbMgrqAskpSRkZSxjLNUmnMPkPBzmga5E8zp+tzSaroqqtuPvm1AhKhwMuxFYc9FtC8CW67b9uR/gWC9tHNVLvz43HXqxHWOlbfDqssf4642JHjTBTaxEFsD56o9DKoVNsjIwLe3cG13eqldL5xiizHWJJCAy+CarDGRVEXOsaZgUi4SoazeGsHSEajNlJCtqId5/JTKsVODLwj+s+9Bt89gZ/7ieS5YtzqRinuO0= igortiunov@gmail.com"
storage:
  directories:
    - path: /var/lib/cloud/data
      overwrite: true
    - path: /var/lib/heat-cfntools
      overwrite: true
  files:
    - path: /etc/selinux/config
      overwrite: true
      mode: 0644
      contents:
        inline: |
          SELINUX=__SELINUX_MODE__
          SELINUXTYPE=targeted
    - path: /etc/containers/libpod.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          # Maximum size of log files (in bytes)
          # -1 is unlimited
          # 50m
          max_log_size = 52428800
    - path: /etc/hostname
      mode: 0644
      overwrite: true
      contents:
        inline: |
          __HOSTNAME__
    - path: /etc/pki/ca-trust/source/anchors/openstack-ca.pem
      mode: 0644
      overwrite: true
      contents:
        inline: |
          __OPENSTACK_CA__
    - path: /root/configure-agent-env.sh
      mode: 0754
      overwrite: true
      contents:
        inline: |
          #!/bin/bash

          set -x
          set -e
          set +u

          until [ -f /etc/pki/ca-trust/source/anchors/openstack-ca.pem ]
          do
              echo "waiting for /etc/pki/ca-trust/source/anchors/openstack-ca.pem"
              sleep 3s
          done

          /usr/bin/update-ca-trust
          mkdir /etc/kubernetes/
          cp /etc/pki/tls/certs/ca-bundle.crt /etc/kubernetes/ca-bundle.crt

          # Create a keypair for the heat-container-agent to
          # access the node over ssh. It is useful to operate
          # in host mount namespace and apply configuration.
          id
          mkdir -p /srv/magnum/.ssh
          chmod 0700 /srv/magnum/.ssh
          #touch /srv/magnum/.ssh/heat_agent_rsa
          ssh-keygen -q -t rsa -N '' -f /tmp/heat_agent_rsa
          mv /tmp/heat_agent_rsa /srv/magnum/.ssh/heat_agent_rsa
          mv /tmp/heat_agent_rsa.pub /srv/magnum/.ssh/heat_agent_rsa.pub
          chmod 0400 /srv/magnum/.ssh/heat_agent_rsa
          chmod 0400 /srv/magnum/.ssh/heat_agent_rsa.pub
          # Add the public to the host authorized_keys file.
          mkdir -p /root/.ssh
          chmod 0700 /root/.ssh
          cat /srv/magnum/.ssh/heat_agent_rsa.pub > /root/.ssh/authorized_keys
          # Add localost to know_hosts
          ssh-keyscan 127.0.0.1 > /srv/magnum/.ssh/known_hosts
          # ssh configguration file, to be specified with ssh -F
          cat > /srv/magnum/.ssh/config <<EOF
          Host localhost
               HostName 127.0.0.1
               User root
               IdentityFile /srv/magnum/.ssh/heat_agent_rsa
               UserKnownHostsFile /srv/magnum/.ssh/known_hosts
          EOF

          sed -i '/^PermitRootLogin/ s/ .*/ without-password/' /etc/ssh/sshd_config
          # Security enhancement: Disable password authentication
          sed -i '/^PasswordAuthentication yes/ s/ yes/ no/' /etc/ssh/sshd_config

          systemctl restart sshd
    - path: /etc/zincati/config.d/90-disable-auto-updates.toml
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [updates]
          enabled = false

systemd:
  units:
    - name: configure-agent-env.service
      enabled: true
      contents: |
        [Unit]
        Description=Configure heat agent environment
        After=sshd.service
        
        [Service]
        User=root
        Group=root
        Type=simple
        ExecStart=/bin/bash /root/configure-agent-env.sh
        Restart=on-failure
        
        [Install]
        WantedBy=multi-user.target
    - name: heat-container-agent.service
      enabled: true
      contents: |
        [Unit]
        Description=Run heat-container-agent
        After=network-online.target configure-agent-env.service
        Wants=network-online.target
        
        [Service]
        EnvironmentFile=-/etc/environment
        ExecStartPre=mkdir -p /var/lib/heat-container-agent
        ExecStartPre=mkdir -p /var/run/heat-config
        ExecStartPre=mkdir -p /var/run/os-collect-config
        ExecStartPre=mkdir -p /opt/stack/os-config-refresh
        ExecStartPre=-mv /var/lib/os-collect-config/local-data /var/lib/cloud/data/cfn-init-data
        ExecStartPre=mkdir -p /srv/magnum
        ExecStartPre=-/bin/podman kill heat-container-agent
        ExecStartPre=-/bin/podman rm heat-container-agent
        ExecStartPre=-/bin/podman pull __CONTAINER_INFRA_PREFIX__heat-container-agent:__HEAT_CONTAINER_AGENT_TAG__
        ExecStart=/bin/podman run \
                --name heat-container-agent \
                --privileged \
                --net=host \
                --volume /srv/magnum:/srv/magnum \
                --volume /opt/stack/os-config-refresh:/opt/stack/os-config-refresh \
                --volume /run/systemd:/run/systemd \
                --volume /etc/:/etc/ \
                --volume /var/lib:/var/lib \
                --volume /var/run:/var/run \
                --volume /var/log:/var/log \
                --volume /tmp:/tmp \
                --volume /dev:/dev \
                --env REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
                __CONTAINER_INFRA_PREFIX__heat-container-agent:__HEAT_CONTAINER_AGENT_TAG__ \
                /usr/bin/start-heat-container-agent
        TimeoutStartSec=10min
        Restart=on-failure
        RestartSec=30s

        ExecStop=/bin/podman stop heat-container-agent
        
        [Install]
        WantedBy=multi-user.target
