---
heat_template_version: rocky

parameters:

  private_network:
    type: string
    default: ""

  existing_network:
    type: string
    default: ""

  private_subnet:
    type: string
    default: ""

  existing_subnet:
    type: string
    default: ""

outputs:

  network:
    value: {get_param: existing_network}

  subnet:
    value: {get_param: existing_subnet}
